org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
# org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.9.10-hotspot
# github actions compat
group=com.kishku7
artifactName=Chunksmith
version=3.1.1+1.20.1-mazenzai-compat
description=Pre-generates chunks, quickly, efficiently, and safely. Patched to work with mazenzai's voxy-0.2.13-alpha 1.20.1 backport for 1.20.1
github=https://github.com/DasBrin/Chunksmith/tree/voxy-1201-patch
author=Kishku7 x DasBrin
modId=chunksmith
minecraft_version=1.20.1
fabric_loader_version=0.16.10
fabric_api_version=0.92.2+1.20.1
